server:
  tomcat:
    uri-encoding: utf-8
logging:
  config: classpath:config/logback.xml
spring:
  # http 请求设置
  http:
    multipart:
      enabled: true
      max-file-size: 200Mb
      max-request-size: 200Mb
      resolve-lazily: false
      file-size-threshold: 0
    encoding:
      charset: utf-8
      enabled: true